using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.Serialization;

namespace Mobimp.Edusoft.Data.Common
{
    public enum LookupNames
    {
        [EnumMember]
        Roles,
        [EnumMember]
        Nationality,
        [EnumMember]
        House,
        [EnumMember]
        Employees,
        [EnumMember]
        Users,
        [EnumMember]
        Country,
        [EnumMember]
        Block,
        [EnumMember]
        Warden,
        [EnumMember]
        State,
        [EnumMember]
        District,
        [EnumMember]
        Sex,
        [EnumMember]
        Mgtype,
        [EnumMember]
        Salutation,
        [EnumMember]
        Msalutation,
        [EnumMember]
        Fsalutation,
        [EnumMember]
        StudentCategory,
        [EnumMember]
        SubjectCategory,
        [EnumMember]
        Religion,
        [EnumMember]
        Relationship,
        [EnumMember]
        Fees,
        [EnumMember]
        AdmissionType,
        [EnumMember]
        Class,
        [EnumMember]
        ClassX,
        [EnumMember]
        ExamNames,
        [EnumMember]
        RouteNo,
        [EnumMember]
        PromotionClass,
        [EnumMember]
        PaymentType,
        [EnumMember]
        Cast,
        [EnumMember]
        EmployeeType,
        [EnumMember]
        Designation,
        [EnumMember]
        Department,
        [EnumMember]
        MaritalStatus,
        [EnumMember]
        Academicsession,
        [EnumMember]
        PreviuosYear,
        [EnumMember]
        StaffType,
        [EnumMember]
        StaffCategory,
        [EnumMember]
        Dry,
        [EnumMember]
        Employee,
        [EnumMember]
        TeachingStaff,
        [EnumMember]
        GeneratedStaff,
        [EnumMember]
        Clerk,
        [EnumMember]
        Section,
        [EnumMember]
        Subject,
        [EnumMember]
        SubSubject,
        [EnumMember]
        WeekDays,
        [EnumMember]
        Occupation,
        [EnumMember]
        Stream,
        [EnumMember]
        StudentType,
        [EnumMember]
        Optionalsubjects,
        [EnumMember]
        PayMode,
        [EnumMember]
        FeeTypes,
        [EnumMember]
        StudentFeeTypes,
        [EnumMember]
        FeeTypeswithoutTransport,
        [EnumMember]
        Months,
        [EnumMember]
        Tariff,
        [EnumMember]
        Destination,
        [EnumMember]
        Admissiontype,
        [EnumMember]
        Sectionlist,
        [EnumMember]
        transport,
        [EnumMember]
        BloodGroup,
        [EnumMember]
        BelongToBPLoption,
        [EnumMember]
        MonthlyFeeTypes,
        [EnumMember]
        DefaulterMonths,
        [EnumMember]
        StudentTransportType,
        [EnumMember]
        BoardingStudentType,
        [EnumMember]
        VehicleListwithDriver,
        [EnumMember]
        Remarks,
        [EnumMember]
        CurrentMonths,
        [EnumMember]
        MenuHeader,
        [EnumMember]
        TimeTableGroup,
        [EnumMember]
        Timer,
        [EnumMember]
        RackGroup,
        [EnumMember]
        Template,
        [EnumMember]
        SendTo,
        [EnumMember]
        SmsType,
        [EnumMember]
        Admin,
        [EnumMember]
        RackSubGroup,
        [EnumMember]
        FeeTypeCategory,
        [EnumMember]
        LeaveType,
        [EnumMember]
        LoanType,
        [EnumMember]
        Route,
        [EnumMember]
        TransportVehicleType,
        [EnumMember]
        Campus,
        [EnumMember]
        Wing,
        [EnumMember]
        Group,
        [EnumMember]
        Units,
        [EnumMember]
        SubGroup,
        [EnumMember]
        VendorType,
        [EnumMember]
        OrderType,
        [EnumMember]
        TransactionType,
        [EnumMember]
        AllLedgerHead,
        [EnumMember]
        CollectedBy,
        [EnumMember]
        PaymentMode,
        [EnumMember]
        AccountGroup,
        [EnumMember]
        NatureGroup,
        [EnumMember]
        VendorName,
        [EnumMember]
        BookStoreVendorType,
        [EnumMember]
        BankName,
        [EnumMember]
        ApplicableDays,
        [EnumMember]
        Shift
    }
}
